### ISSUE TITLE
Doesn't post edits to the same user

### ISSUE THREAD

**Issue by TrippW** [TrippW/Reddit-Crawler#3]
If Grafo replies to the same user multiple times over any number of posts, the titles are now the same and anyone past the first will not be posted.

Suggestion: Change how data is stored in txt file to have a struct of
{user, title, image link, parent id, post id}
OR just save the complete dict already used in code
then construct the dict and compare against contents of storage to see if it has already been posted.

**Comment by Fotoratte** [comment]
If you just save the imgur-url in the posted_links.txt you should be save :-)

**Comment by TrippW** [comment]
The only thing is we do need to check for identical title names with different i.reddit urls, otherwise we get reposts since grafo might post the same comic on a few subreddits with identical names.

So I think I'm going to change it to use the following format (Hope I wrote this well enough to understand)

{title:{url:{posted:boolean,contextid:int},comment:boolean}}

That way a title can have any number of urls, if its a comment, posted will post the image and a context link; if it isn't a comment, the context comment on the original will edit itself to add multiple contexts/links to other subreddits.
